services:
  postgres:
    image: timescale/timescaledb:2.1.0-pg13
    ports:
    - '5433:5433'
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
volumes:
  postgres-data: {}