services:
  db:
    image: timescale/timescaledb:2.1.0-pg13
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  api:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
      
volumes:
  postgres-data: {}